version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: nanapay_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nanapay
      POSTGRES_PASSWORD: nanapay
      POSTGRES_DB: nanapay_db
    ports:
      - "5432:5432"
    volumes:
      - nanapay_pgdata:/var/lib/postgresql/data

volumes:
  nanapay_pgdata:
